services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - GENIE_ENV=dev
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
      - GOOGLE_MAPS_MAP_ID=${GOOGLE_MAPS_MAP_ID:-}
      - DB_NAME=${DB_NAME:-}
      - DB_HOST=${DB_HOST:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_PORT=${DB_PORT:-}
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
    command: julia -e "using Pkg; Pkg.activate(\".\"); using Genie; Genie.loadapp(); up(host = \"0.0.0.0\", async = false);"

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ev_location
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
