services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3800:3800"
    environment:
      - GENIE_ENV=prod
      - JWT_SECRET=${JWT_SECRET:-}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
      - GOOGLE_MAPS_MAP_ID=${GOOGLE_MAPS_MAP_ID:-}
      - DB_NAME=${DB_NAME:-}
      - DB_HOST=${DB_HOST:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_PORT=${DB_PORT:-}
    volumes:
      - .:/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /app
    tty: true
    command: julia -e "using Pkg; Pkg.activate(\".\"); using Genie; Genie.loadapp(); up(host = \"0.0.0.0\", async = false);"
